name: Build for Windows x64

on:
  workflow_call:
    inputs:
      tag:
        description: "tag"
        required: false
        default: ""
        type: string
  workflow_dispatch:

jobs:
  build-windows-app:
    name: Release Windows x64
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 windows

      - name: Add fastforge and Inno Setup
        run: |
          dart pub global activate fastforge
          choco install innosetup

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1

      - name: Build Windows
        run: |
          fastforge package --platform windows --targets exe --flutter-build-args="dart-define-from-file=pili_release.json"

      - name: Prepare Upload
        run: |
          mkdir -p Release/cilicili-Win
          mkdir -p cilicili-Win-Setup
          mv build/windows/x64/runner/Release/* Release/cilicili-Win/
          mv dist/**/*.exe cilicili-Win-Setup/cilicili_windows_${{env.version}}_x64_setup.exe

      - name: Compress
        run: |
          Compress-Archive -Path "Release/cilicili-Win" -DestinationPath "cilicili_windows_${{env.version}}_x64_portable.zip"
        shell: pwsh

      - name: Create Release
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          body: |
            ## cilicili ${{ github.event.inputs.tag }} Windows x64
            
            🪟 Windows 版本
            
            ### 下载
            - **安装版**: cilicili_windows_*_x64_setup.exe
            - **便携版**: cilicili_windows_*_x64_portable.zip
          files: |
            cilicili_windows_*.zip
            cilicili-Win-Setup/cilicili_windows_*.exe

      - name: Upload windows file release
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: Windows-file-x64-release
          path: cilicili_windows_*.zip

      - name: Upload windows setup release
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: Windows-setup-x64-release
          path: cilicili-Win-Setup/cilicili_windows_*.exe
